name: JQF github actions
on: 
  push:
      branches: [master]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: fuzzing with Gradle
        run: ./gradlew fuzz --class=com.mborzenkov.examplejavagradle.ExampleTestClass --method=exampleMethod --time=10s
